// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const PROJECT_ID = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim();
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() || (PROJECT_ID ? `https://${PROJECT_ID}.supabase.co` : '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const FALLBACK_URL = 'https://placeholder.supabase.co';
const FALLBACK_KEY = 'placeholder-anon-key';

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const missingSupabaseEnvVars = [
  !SUPABASE_URL ? 'VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID)' : null,
  !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
].filter(Boolean) as string[];

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const disabledFetch: typeof fetch = async () =>
  new Response(
    JSON.stringify({
      message: `Supabase is not configured. Missing env vars: ${missingSupabaseEnvVars.join(', ')}`,
    }),
    { status: 503, headers: { 'Content-Type': 'application/json' } }
  );

export const supabase = createClient<Database>(
  isSupabaseConfigured ? SUPABASE_URL : FALLBACK_URL,
  isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY : FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    ...(isSupabaseConfigured ? {} : { global: { fetch: disabledFetch } }),
  }
);
